spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) sql 쿼리 출력
    properties:
      hibernate:
        format_sql: true # (3) SQL pretty print
  datasource:
    url: jdbc:mysql://{AWS RDS Endpoint}/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: {RDS Mysql Admin id}
    password: {RDS Mysql Admin password}
    driver-class-name: com.mysql.cj.jdbc.Driver
config:
  domain: {AWS S3 Endpoint}
server:
  servlet:
    encoding:
      force-response: true
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 4200
  refresh-token-expiration-minutes: 420